load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
  name = "APP_test",
  size = "small",
  srcs = glob(["Test1.cpp"]),
  copts = ["-Iexternal/gtest/include"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//applib:APPLib"
    ],
)

cc_test(
  name = "APP_test_2",
  size = "small",
  srcs = glob(["Test2.cpp"]),
  copts = ["-Iexternal/gtest/include"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//applib:APPLib"
    ],
)

cc_test(
  name = "APP_test_3",
  size = "small",
  srcs = glob(["Test3.cpp"]),
  copts = ["-Iexternal/gtest/include"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//applib:APPLib"
    ],
)

cc_test(
  name = "APP_test_4",
  size = "small",
  srcs = glob(["Test4.cpp"]),
  copts = ["-Iexternal/gtest/include"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//applib:APPLib"
    ],
)

cc_test(
  name = "APP_test_5",
  size = "small",
  srcs = glob(["Test5.cpp"]),
  copts = ["-Iexternal/gtest/include"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//applib:APPLib"
    ],
)

cc_test(
  name = "APP_test_6",
  size = "small",
  srcs = glob(["Test6.cpp"]),
  copts = ["-Iexternal/gtest/include"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//applib:APPLib"
    ],
)

cc_test(
  name = "APP_test_7",
  size = "small",
  srcs = glob(["Test7.cpp"]),
  copts = ["-Iexternal/gtest/include"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//applib:APPLib"
    ],
)

