name: GTest
on:
  push:
    branches: [ main, SCT ]
  pull_request:
    branches: [ main, SCT ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone GTest
      run:  git clone https://github.com/google/googletest.git
    - name: Install gtest manually
      working-directory: ./googletest
      run:  sudo apt install python3-pip &&
            cmake . &&
            make &&
            sudo make install
    - name: Install Bazel
      run: sudo npm install -g @bazel/bazelisk
    - uses: actions/checkout@v1
    #using the create-output.sh as a guide...
    - name: g++ compilation
      run:  g++ -g -std=c++14 -Wall -Wextra -Wno-sign-compare applib/*.cpp  -o bld.out building.cpp
    - name: clang tidy build
      run: clang++ -g -std=c++14 -Wall -Wextra -Wno-sign-compare applib/*.cpp building.cpp    
    - name: Install Valgrind
      run:  sudo apt update;
            sudo apt install -y valgrind
    - name: run it
      run: valgrind --leak-check=full --errors-for-leak-kinds=definite --track-origins=yes --error-exitcode=3 ./bld.out




  Run_Test_1:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Clone GTest
      run:  git clone https://github.com/google/googletest.git
    - name: Install gtest manually
      working-directory: ./googletest
      run:  sudo apt install python3-pip &&
            cmake . &&
            make &&
            sudo make install
    - name: Install Bazel
      run: sudo npm install -g @bazel/bazelisk
    - name: Install Valgrind
      run:  sudo apt update;
            sudo apt install -y valgrind
    - uses: actions/checkout@v1
    - name: Run Test
      run:  bazel test --cxxopt=-std=c++14 --verbose_failures --run_under='/usr/bin/valgrind --leak-check=full --errors-for-leak-kinds=definite --error-exitcode=3' --test_output=all //Tests:APP_test

      #Note to add /remove tests:
      # 1) make the job here Run_Test_#
      # 2) copy the content from one of the run tests (not build)
      # 3) modify the Build file in the testing folder that holds these test scripts.

      # additional note, user code expected in: applib
      # note, maze data files in: maze.
        #if more need to be added later, add it to the export list in the build file in data folder
